
USE DW_MARKETING
GO

DROP TABLE IF EXISTS CampaignMethods;
DROP TABLE IF EXISTS MarketingCampaign;
DROP TABLE IF EXISTS Method;
DROP TABLE IF EXISTS Junk;
DROP TABLE IF EXISTS Property;
DROP TABLE IF EXISTS DimDate;
