insert into holidays ("date", "holiday", "bank_holiday") values ('2015-01-06', 'The Epiphany', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2015-01-21', 'Grandmother’s day', 0);
insert into holidays ("date", "holiday", "bank_holiday") values ('2015-01-22', 'Grandfather’s day', 0);
insert into holidays ("date", "holiday", "bank_holiday") values ('2015-05-01', 'Labour Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2015-05-03', 'Constitution Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2015-11-11', 'Independence Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2015-12-25', 'Christmas', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2015-04-06', 'Easter Monday', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2015-06-04', 'Corpus Christi', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2016-01-06', 'The Epiphany', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2016-01-21', 'Grandmother’s day', 0);
insert into holidays ("date", "holiday", "bank_holiday") values ('2016-01-22', 'Grandfather’s day', 0);
insert into holidays ("date", "holiday", "bank_holiday") values ('2016-05-01', 'Labour Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2016-05-03', 'Constitution Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2016-11-11', 'Independence Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2016-12-25', 'Christmas', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2016-03-28', 'Easter Monday', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2016-05-26', 'Corpus Christi', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2017-01-06', 'The Epiphany', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2017-01-21', 'Grandmother’s day', 0);
insert into holidays ("date", "holiday", "bank_holiday") values ('2017-01-22', 'Grandfather’s day', 0);
insert into holidays ("date", "holiday", "bank_holiday") values ('2017-05-01', 'Labour Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2017-05-03', 'Constitution Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2017-11-11', 'Independence Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2017-12-25', 'Christmas', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2017-04-17', 'Easter Monday', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2017-06-15', 'Corpus Christi', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2018-01-06', 'The Epiphany', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2018-01-21', 'Grandmother’s day', 0);
insert into holidays ("date", "holiday", "bank_holiday") values ('2018-01-22', 'Grandfather’s day', 0);
insert into holidays ("date", "holiday", "bank_holiday") values ('2018-05-01', 'Labour Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2018-05-03', 'Constitution Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2018-11-11', 'Independence Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2018-12-25', 'Christmas', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2018-04-02', 'Easter Monday', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2018-05-31', 'Corpus Christi', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2019-01-06', 'The Epiphany', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2019-01-21', 'Grandmother’s day', 0);
insert into holidays ("date", "holiday", "bank_holiday") values ('2019-01-22', 'Grandfather’s day', 0);
insert into holidays ("date", "holiday", "bank_holiday") values ('2019-05-01', 'Labour Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2019-05-03', 'Constitution Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2019-11-11', 'Independence Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2019-12-25', 'Christmas', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2019-04-22', 'Easter Monday', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2019-06-20', 'Corpus Christi', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2020-01-06', 'The Epiphany', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2020-01-21', 'Grandmother’s day', 0);
insert into holidays ("date", "holiday", "bank_holiday") values ('2020-01-22', 'Grandfather’s day', 0);
insert into holidays ("date", "holiday", "bank_holiday") values ('2020-05-01', 'Labour Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2020-05-03', 'Constitution Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2020-11-11', 'Independence Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2020-12-25', 'Christmas', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2020-04-13', 'Easter Monday', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2020-06-11', 'Corpus Christi', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2021-01-06', 'The Epiphany', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2021-01-21', 'Grandmother’s day', 0);
insert into holidays ("date", "holiday", "bank_holiday") values ('2021-01-22', 'Grandfather’s day', 0);
insert into holidays ("date", "holiday", "bank_holiday") values ('2021-05-01', 'Labour Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2021-05-03', 'Constitution Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2021-11-11', 'Independence Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2021-12-25', 'Christmas', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2021-04-05', 'Easter Monday', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2021-06-03', 'Corpus Christi', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2022-01-06', 'The Epiphany', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2022-01-21', 'Grandmother’s day', 0);
insert into holidays ("date", "holiday", "bank_holiday") values ('2022-01-22', 'Grandfather’s day', 0);
insert into holidays ("date", "holiday", "bank_holiday") values ('2022-05-01', 'Labour Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2022-05-03', 'Constitution Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2022-11-11', 'Independence Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2022-12-25', 'Christmas', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2022-04-18', 'Easter Monday', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2022-06-16', 'Corpus Christi', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2023-01-06', 'The Epiphany', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2023-01-21', 'Grandmother’s day', 0);
insert into holidays ("date", "holiday", "bank_holiday") values ('2023-01-22', 'Grandfather’s day', 0);
insert into holidays ("date", "holiday", "bank_holiday") values ('2023-05-01', 'Labour Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2023-05-03', 'Constitution Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2023-11-11', 'Independence Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2023-12-25', 'Christmas', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2023-04-10', 'Easter Monday', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2023-06-08', 'Corpus Christi', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2024-01-06', 'The Epiphany', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2024-01-21', 'Grandmother’s day', 0);
insert into holidays ("date", "holiday", "bank_holiday") values ('2024-01-22', 'Grandfather’s day', 0);
insert into holidays ("date", "holiday", "bank_holiday") values ('2024-05-01', 'Labour Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2024-05-03', 'Constitution Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2024-11-11', 'Independence Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2024-12-25', 'Christmas', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2024-04-01', 'Easter Monday', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2024-05-30', 'Corpus Christi', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2025-01-06', 'The Epiphany', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2025-01-21', 'Grandmother’s day', 0);
insert into holidays ("date", "holiday", "bank_holiday") values ('2025-01-22', 'Grandfather’s day', 0);
insert into holidays ("date", "holiday", "bank_holiday") values ('2025-05-01', 'Labour Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2025-05-03', 'Constitution Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2025-11-11', 'Independence Day', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2025-12-25', 'Christmas', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2025-04-21', 'Easter Monday', 1);
insert into holidays ("date", "holiday", "bank_holiday") values ('2025-06-19', 'Corpus Christi', 1);